# fly.toml app configuration file generated for festrip-tickets on 2023-05-15T13:03:47+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "festrip-tickets"
primary_region = "mad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
